Minor formatting and style definitions
IEvangelist/azure-cosmos-dotnet-repository pull request #9
Opened 2020-10-18 03:16 UTC by wforney

- Sealed the attribute
- Separate file per class
- Whitespace handling set to tab and let indent/tab size float (allows user to define tab width in their editor)
- Added editorconfig settings for most things, except sort order, kept preferences from existing project... except set warning on using outside namespace, but didn't move them inside

After this I will pull in the resource file changes for localization.

2020-10-18 04:27 UTC, wforney commented
- Moved all strings to use resources
- Switched setting to put usings outside namespace to match previous code

2020-10-18 06:36 UTC, wforney commented
- Added cancellation tokens to all repository async methods
- Added null argument checks

2020-10-19 12:40 UTC, IEvangelist requested changes
Hi @wforney - Is there any way you could give a pull request with just a few of these changes? For example, `sealed`, new file for class, new `Constants` class, `Resources`, and then that's it? Then from there we'll look again at what is needed - I have already been working on some of the other parts, like `CancellationToken`, etc.

2020-10-23 13:00 UTC, IEvangelist commented
Addressed a lot of this in https://github.com/IEvangelist/azure-cosmos-dotnet-repository/commit/1c944b7c3b9ceecfd66204a3208e5309a4884215 and https://github.com/IEvangelist/azure-cosmos-dotnet-repository/commit/227c05d00fa7a7e03487e05417c70a8104a8f133. Thanks for these contributions.

2020-10-23 13:00 UTC, closed without merging

2020-10-23 13:39 UTC, wforney commented on Microsoft.Azure.CosmosRepository/src/Attributes/PartitionKeyPathAttribute.cs
> +	/// <summary>
If you use tabs you can set the tab width to 4 spaces in your editor. Other people can change it to what they want. You just force them to your preference by forcing spaces.

2020-10-23 13:40 UTC, wforney commented on Microsoft.Azure.CosmosRepository/src/Constants.cs
> +	public static class Constants
No particular reason.

2020-10-23 13:41 UTC, wforney commented
Cool, I hadn't had time during the week to mess with this.